pull_request_rules:
  - name: Automatic merge for renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=buildkite/baseweb
    actions:
      merge:
        method: squash
        # because of the setting below, PRs will be automatially updated with the latest master
        strict: true

  - name: Automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=buildkite/baseweb
    actions:
      merge:
        method: squash
        # because of the setting below, PRs will be automatially updated with the latest master
        strict: true

  - name: Automatic merge for master when CI passes and has 2 approvals
    conditions:
      - '#approved-reviews-by>=2'
      - status-success=buildkite/baseweb
      - status-success=probot/pr-label
      - status-success=license/cla
      - status-success=ci/codesandbox
      - status-success=now
      - base=master
      - -draft
      - label!=work in progress
    actions:
      merge:
        method: squash
        # because of the setting below, PRs will be automatially updated with the latest master
        strict: true
