pull_request_rules:
  - name: Automatic merge for renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=buildkite/baseweb
    actions:
      merge:
        method: squash
