version: '2.3'
services:
  # to run selenium with chrome locally
  chrome-standalone:
    image: selenium/standalone-chrome:latest@sha256:da91acc1e0c63d5d7bfebc3d1e31652787c6227543d39d6df433837a0e81583a
    network_mode: 'host'
    restart: always
    ports:
      - '4444:4444'

  e2e-test-chrome:
    build: .
    network_mode: 'host'
    depends_on:
      - chrome-standalone
      - e2e-server-healthy
    command: yarn e2e:test
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub

  # this spins up a server that serves the html/js/css for the e2e tests
  e2e-server:
    build: .
    command: yarn e2e:serve
    expose:
      - 8080
    ports:
      - '8080:8080'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -H "Accept: text/html" -f http://localhost:8080 || exit 1',
        ]
      interval: 5s
      timeout: 10s
      retries: 5

  # tests if the e2e-server is ready to serve traffic
  e2e-server-healthy:
    build: .
    network_mode: 'host'
    depends_on:
      e2e-server:
        condition: service_healthy

  # running the e2e tests in ci
  e2e-test:
    build: .
    network_mode: 'host'
    depends_on:
      - e2e-server-healthy
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT

  baseui:
    build: .
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - SCREENER_API_KEY
