ID="5cc25d24-2f53-4efa-9f63-2c30eea59df4"

[build]
  publish = "public/"
  command = "yarn install --production=false && yarn documentation:build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/components/gallery"
  to = "/components"
