steps:
  - name: ':docker: :package: e2e'
    plugins:
      'docker-compose#v3.0.3':
        build:
          - e2e-test
          - e2e-server
          - e2e-server-healthy
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: 'Visual regression tests'
    command: yarn vrt:ci
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
        pull:
          - e2e-server
          - e2e-server-healthy
    agents:
      queue: builders
    artifact_paths:
      - '__artifacts__/*.png'
